automation: אוטומציה
chart: תרשימים
configuration: הגדרות
editPage: עריכת עמוד
help:
  documentation: תעוד מערכת
  feedback: שליחת משוב
  forum: עזרה
  version: 'גרסה:'
module: מודולות
more: פריטים נוספום
namespace: אפליקציות
noPageTitle: אין כותרת עמוד
page: עמודים
userSettings:
  changePassword: שינוי סיסמה
  loggedInAs: משתמש מחובר {{user}}
  logout: התנתקות
  profile: פרופיל אישי
viewPage: הצגת עמוד
