automation: אוטומציה
chart: Charts
configuration: Configuration
editPage: עריכת עמוד
help:
  documentation: תעוד מערכת
  feedback: שליחת משוב
  forum: עזרה
  version: 'גרסה:'
module: Modules
more: More
namespace: Namespaces
noPageTitle: No page title
page: Pages
userSettings:
  changePassword: שינוי סיסמה
  loggedInAs: משתמש מחובר {{user}}
  logout: התנתקות
  profile: פרופיל אישי
viewPage: View Page
